config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'pages/index', to: 'pages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users

  resources :categories, except: [:destroy] 

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum:3, maximum:50}
  validates :description, presence: true, length: {minimum:10, maximum: 300}
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-\.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email , presence: true, uniqueness: {case_sensitive: false}, length: {maximum:105}, format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in"
      redirect_to pages_home_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index]
  before_action :require_same_user, only: [:edit, :update, :delete]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    user = User.find(session[:user_id])
    @article.user = user
    if @article.save
      flash[:success]= "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end

  def update
    @article.user = User.first
    if @article.update(article_params)
    
      flash[:success] = "Successfully updated the article"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def edit  
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article successfully deleted"
    redirect_to articles_path
  end
 
 
  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end
  
    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "You do not have authentication to edit other user's articles"
        redirect_to users_path
      end
    end
 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_user
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Not enough authentication"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome to Alpha Blog, #{user.username}"
      redirect_to user_path(user)
    else
      flash[:danger] = "Username or/and password is/are incorrect"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Successfully logged out"
    redirect_to pages_home_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user , only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
 
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success]="Welcome to Alpha Blog, #{@user.username}"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Account updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:danger] = "Successfully deleted the user"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end

  def set_user
     @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "Not enough authentication"
      redirect_to users_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin can perform this action"
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options={size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj:@article %>
<div class="row	">
  <div class="col-sm-12">	
    <%= form_for(@article, :html=>{class:"form-horizontal",role: "form"}) do |f| %>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title,class: "form-control", placeholder: "Title", autofocus:true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-2 control-label"> 
          <%= f.label :description %>
        </div>
        <div class="col-sm-8"> 
           <%= f.text_area :description, class:"form-control", placeholder: "Description of Article" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class:'btn btn-primary btn-lg' %>
        </div>
      </div>
      <% end %>
    
      <div class="col-sm-offset-4 col-sm-4">
     [ <%= link_to 'Cancel Request and return to articles listing', articles_path %> ]
      </div>
  </div>
</div>

app/views/articles/_listartciles.html.erb
<% obj.each do |article| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">

      <div class="article-title">
          <%= link_to article.title, article_path(article) %>
      </div>

      <div class="article-body">
        <%=truncate(article.description, length:100) %>
        <div class="article-meta-details">
        <small>Created by <%= article.user.username if article.user %>,
                <%=time_ago_in_words(article.created_at) %> ago,
                updated at: <%= time_ago_in_words(article.updated_at)%> ago</small>
        </div>
      </div>
     
      <div class="article_categories"> 
      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %></p>
      <% end %>
      </div>


      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
      <div class="article-actions">
        <%= link_to "Delete", article_path(article), method: :delete,
        data: {confirm:"Are you sure you want to delete the article?"}, class: "btn btn-md btn-danger" %>
        <%= link_to 'Edit Article', edit_article_path(article), class: "btn btn-md btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/articles/destroy.html.erb
<h2> Deleted Article </h2>
 

app/views/articles/edit.html.erb
<h2 align="center"><strong> Editing Article</strong></h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<h2 align="center"><strong> Listing of all Articles</strong> </h2>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'listartciles', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div> 

app/views/articles/new.html.erb
<h1 align="center"> Create Article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"><strong>Title: <%= @article.title %></strong></h2>
  <div class="well col-sm-8 col-sm-offset-2">
    <div align="center">
    <div class="row center">
      <div class="col-md-4 col-md-offset-4">
        <div class="listing">
          <li>Created By:</li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <div class="article-title" style="margin-left:10px;"><%= link_to @article.user.username, user_path(@article.user) %></div>
          <div><%= pluralize(@article.user.articles.count, "articles") %></div>
        </div>
      </div>
    </div>
    </div>

    <h3 align="center"><strong>Description:</strong></h4>
    <hr>
     <h4> <%= simple_format(@article.description) %></h4>

    <div class="article_categories">
      <% if @article.categories.any? %>
        <p>Categories: <%= render @article.categories %></p>
      <% end %>
    </div>

    <div class="article-actions">
    <%= link_to 'List all Articles', articles_path, class: "btn btn-md btn-success" %>
   <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
     <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm:"Are you sure you want to delete the article?"}, class: "btn btn-md btn-danger" %>
     <%= link_to 'Edit Article', edit_article_path(@article), class: "btn btn-md btn-primary" %>
   <% end %>
  </div>
 </div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>&nbsp;</span>

app/views/categories/index.html.erb
<h1 align="center"><strong>All Categories</strong></h1>

<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <div class="row center">
      <div class="well col-md-4 col-md-offset-4">
        <div align="center" style="font-size:20px;font-weight:bold;"><%= link_to category.name.upcase, category_path(category) %></div>
	<div align="center" style="margin-top:10px;font-color:#707070;"><%= pluralize(category.articles.count, "article") %></div>
      </div>
    </div>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Add new Category</h1>

<%= render 'shared/errors', obj:@category %>
<div class="row ">
  <div class="col-sm-12">
    <%= form_for(@category, :html=>{class:"form-horizontal",role: "form"}) do |f| %>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name,class: "form-control", placeholder: "Category Name", autofocus:true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Create Category", class:'btn btn-primary btn-lg' %>
        </div>
      </div>
      <% end %>

      <div class="col-sm-offset-4 col-sm-4">
     [ <%= link_to 'Cancel Request and return to articles listing', articles_path %> ]
      </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 align="center"><strong><span style="text-transform:capitalize;"><%= @category.name %></span> Articles</strong></h1>

<div align="center">
  <%= will_paginate @articles%>
</div>
  <%= render 'articles/listartciles', obj:@articles %>
<div align="center">
  <%= will_paginate @articles%>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>Copyright &copy; by Karan Panchal </small>
    <nav>
      <ul>
        <li><%= link_to 'About', pages_about_path %></li>
      </ul>
    </nav> 
 </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}"%>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg,  :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>
  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <!-- <a class="navbar-brand" id="logo" href="#">Alpha Blog</a>-->
      <%= link_to 'Alpha Blog', pages_home_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <!--<li><a href="#">Linker <span class="sr-only">(current)</span></a></li>-->
        <li><%= link_to 'Article', articles_path, id: "article" %></li> 
        <li><%= link_to 'Users', users_path %></li>

        <% if logged_in? %>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
           <ul class="dropdown-menu">
            <!-- <li><a href="#">Action</a></li>-->
             <li><%= link_to 'Create Article', new_article_path, id:'action' %>
             <li><a href="#">Another action</a></li>
             <li><a href="#">Something else here</a></li>
             <li role="separator" class="divider"></li>
             <li><a href="#">Separated link</a></li>
             <li role="separator" class="divider"></li>
             <li><a href="#">One more separated link</a></li>
           </ul>
         </li>
        <% end %>
        
	 <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
           <ul class="dropdown-menu">
		<li style="font-size:20px;"><%= link_to "All Categories", categories_path %></li>
             <% Category.all.each do |category| %>
		<li><%= link_to "#{category.name}".upcase, category_path(category) %></li>
	     <% end %>
	     <% if logged_in? && current_user.admin? %>
               <li role="separator" class="divider"></li>
	       <li><%= link_to "Create new Category", new_category_path %></li>
	     <% end %>
           </ul>
         </li>

     
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
         <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
           <ul class="dropdown-menu">
             <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
             <li><%= link_to 'View Profile', user_path(current_user) %></li>
             <li><a href="#">Something else here</a></li>
             <li role="separator" class="divider"></li>
             <li><a href="#">Separated link</a></li>
           </ul>
         </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
  <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<h1> Hello, You are now in Abouts Page</h1>
<h2> Rails is really a good framework</h2>

<%= link_to 'Home', pages_home_path %>
<%= link_to 'Index', pages_index_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>ALPHA BLOG</h1>
  <%= link_to 'Sign Up', new_user_path, class: 'btn btn-danger btn-lg btn-xlarge' %>
</div>

app/views/pages/index.html.erb
<h1>This is the index page for alpha-blog app</h1>


<%= link_to 'Home', pages_home_path %>
<%= link_to 'About', pages_about_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
     <div class="col-xs-8 col-xs-offset-2">
       <div class="panel panel-danger">
         <div class="panel-heading">
           <h2 class="panel-title"> 
             <%= pluralize(obj.errors.count, "error") %>
prevented from getting data saved in the database
           </h2>
           <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
           </div>
         </div>
       </div>
     </div>
   </div>
<% end %>

app/views/users/_editform.html.erb
<%= render 'shared/errors', obj:@user %>
<div class="row ">
  <div class="col-sm-12">
    <%= form_for(@user, :html=>{class:"form-horizontal",role: "form"}) do |f| %>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username,class: "form-control", placeholder: "Username", autofocus:true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
           <%= f.email_field :email, class:"form-control", placeholder: "Enter Email" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
           <%= f.password_field :password, class:"form-control", placeholder: "Enter password" %>
        </div>
      </div>


      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class:'btn btn-primary btn-lg') %>
        </div>
      </div>
      <% end %>

      <div class="col-sm-offset-4 col-sm-4">
     [ <%= link_to 'Cancel Request and return to articles listing', articles_path %> ]    

app/views/users/edit.html.erb
<h2 align="center">Edit Account</h2>

<%= render 'editform' %>

app/views/users/index.html.erb
<h2 align="center"><strong> Listing all Users</strong></h2>
<div align="center">
 <div align="center"><%= will_paginate @users %></div>
  <% @users.each do |user| %>
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <div class="listing">
          <%= link_to gravatar_for(user, size: 150), user_path(user) %>
          <div class="article-title" style="margin-left:10px;"><%= link_to user.username, user_path(user) %></div>
          <div><%= pluralize(user.articles.count, "articles") %></div>
          <% if logged_in? and current_user.admin? %>
            <div><%= link_to 'Delete the user and all its articles', user_path(user), method: :delete, data:{confirm: "Are you sure you want to delete the user and all its articles"}, class: "btn btn-danger btn-sm" %></div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div align="center"><%= will_paginate @users %></div>
</div>

app/views/users/new.html.erb
<h2 align="center"> Sign Up for Alpha Blog App</h2>  

<%= render 'editform' %>

app/views/users/show.html.erb
<h2 align="center"> Welcome to <%= @user.username %>'s page</h2>
<div class="row center">
  <div class="col-sm-4 col-sm-offset-5 center">
    <%= gravatar_for @user,size: 150 %>
  </div>
</div>

<h4 align="center"><%= @user.username %>'s Articles</h4>

<div align="center">
  <%= will_paginate @user_articles%>
</div>
<%= render 'articles/listartciles', obj: @user_articles %>
<div align="center">
  <%= will_paginate @user_articles%>
</div>